### ISSUE TITLE
Loadouts not being able to load

### ISSUE THREAD

**Issue by Fluitketel** [Fluitketel/dep-falcons#2]
Not being able to load loadouts saved in the arsenal, seems universal, most likely something in the generic items?

**Comment by Flipachu** [comment]
Trialed 2 loadouts, 1 with tf radio, 1 without, seems it could be to do with saving radios inyour kit. Needs further testing to fully verify.

**Comment by Flipachu** [comment]
Not saving radios in arsenal appears to have fixed this, maybe add radios to an add action on the ammocrate and remove from arsenal. Wait for final decision on radio mods/radios used.
